server:
  port: 8761

eureka:
  instance:
    hostname: localhost2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

  server:
    enable-self-preservation: true